potek_harmonikov('real_xs')
potek_harmonikov('real_ys')
potek_harmonikov('real_xd')
potek_harmonikov('real_yd')
% tex_izpis_potekov('real_xs')
% tex_izpis_potekov('real_ys')
% tex_izpis_potekov('real_xd')
% tex_izpis_potekov('real_yd')

potek_sincos('real_xs', 1)
potek_sincos('real_ys', 1)
potek_sincos('real_xd', 1)
potek_sincos('real_yd', 1)
% tex_izpis_potekov_sincos('real_xs')
% tex_izpis_potekov_sincos('real_ys')
% tex_izpis_potekov_sincos('real_xd')
% tex_izpis_potekov_sincos('real_yd')
%%
potek_harmonikov('lin_xs')
potek_harmonikov('lin_ys')
potek_harmonikov('lin_xd')
potek_harmonikov('lin_yd')
% tex_izpis_potekov('lin_xs')
% tex_izpis_potekov('lin_ys')
% tex_izpis_potekov('lin_xd')
% tex_izpis_potekov('lin_yd')

potek_sincos('lin_xs', 1)
potek_sincos('lin_ys', 1)
potek_sincos('lin_xd', 1)
potek_sincos('lin_yd', 1)
% tex_izpis_potekov_sincos('lin_xs')
% tex_izpis_potekov_sincos('lin_ys')
% tex_izpis_potekov_sincos('lin_xd')
% tex_izpis_potekov_sincos('lin_yd')

%%
prikaz_napake('real_xs',0.2,1)
prikaz_napake('real_ys',0.2,1)
prikaz_napake('real_xd',0.2,1)
prikaz_napake('real_yd',0.2,1)
prikaz_napake('lin_xs',0.2,1)
prikaz_napake('lin_ys',0.2,1)
prikaz_napake('lin_xd',0.2,1)
prikaz_napake('lin_yd',0.2,1)
close all
prikaz_napake('real_xs',0.0,0)
prikaz_napake('lin_xs',0.0,0)

%%
tex_izpis_potekov('meritev_xs')
tex_izpis_potekov('meritev_ys')
tex_izpis_potekov('meritev_xd')
tex_izpis_potekov_sincos('meritev_xs')
tex_izpis_potekov_sincos('meritev_ys')
tex_izpis_potekov_sincos('meritev_xd')


