function tex_izpis_potekov_sincos(meritev)
load Rezultati_simulacij.mat
load Rezultati_meritve.mat


eval(strcat('podatki=',meritev,';'))
tx = ['\Delta ',meritev(end-1),'_',meritev(end)];

fftSin = mojfft(podatki.sin);
fftCos = mojfft(podatki.cos);

yOff = [fftSin{1}(:,1).* cosd(fftSin{2}(:,1)), ...
    fftCos{1}(:,1).* cosd(fftCos{2}(:,1))];

y1st =[fftSin{1}(:,2), fftCos{1}(:,2)];
y1stPh =[fftSin{2}(:,2)+90, fftCos{2}(:,2)];

x = podatki.displacement;


fitSinOff=polyfit(x,yOff(:,1),3);
fitCosOff=polyfit(x,yOff(:,2),3);

fitSinAmp=polyfit(x,y1st(:,1),3);
fitCosAmp=polyfit(x,y1st(:,2),3);

fitSinF=polyfit(x,y1stPh(:,1),3);
fitCosF=polyfit(x,y1stPh(:,2),3);


test{1}= ['&A_{sin} = ',num2str(fitSinAmp(1),'%+.2e'),tx,'^3',...
    num2str(fitSinAmp(2),'%+.2e'),tx,'^2', ...
    num2str(fitSinAmp(3),'%+.2e'),tx,'', ...
    num2str(fitSinAmp(4),'%+.2e'),'\\'];
test{2}= ['&Off_{sin} = ',num2str(fitSinOff(1),'%+.2e'),tx,'^3',...
    num2str(fitSinOff(2),'%+.2e'),tx,'^2', ...
    num2str(fitSinOff(3),'%+.2e'),tx,'', ...
    num2str(fitSinOff(4),'%+.2e'),'\\'];
test{3}= ['&\delta_{sin} = ',num2str(fitSinF(1),'%+.2e'),tx,'^3',...
    num2str(fitSinF(2),'%+.2e'),tx,'^2', ...
    num2str(fitSinF(3),'%+.2e'),tx,'', ...
    num2str(fitSinF(4),'%+.2e'),'\\'];
test{4}= ['&A_{cos} = ',num2str(fitCosAmp(1),'%+.2e'),tx,'^3',...
    num2str(fitCosAmp(2),'%+.2e'),tx,'^2', ...
    num2str(fitCosAmp(3),'%+.2e'),tx,'', ...
    num2str(fitCosAmp(4),'%+.2e'),'\\'];
test{5}= ['&Off_{cos} = ',num2str(fitCosOff(1),'%+.2e'),tx,'^3',...
    num2str(fitCosOff(2),'%+.2e'),tx,'^2', ...
    num2str(fitCosOff(3),'%+.2e'),tx,'', ...
    num2str(fitCosOff(4),'%+.2e'),'\\'];
test{6}= ['&\delta_{cos} = ',num2str(fitCosF(1),'%+.2e'),tx,'^3',...
    num2str(fitCosF(2),'%+.2e'),tx,'^2', ...
    num2str(fitCosF(3),'%+.2e'),tx,'', ...
    num2str(fitCosF(4),'%+.2e'),''];
for i=1:6
    test{i}(strfind(test{i},'.')) = ',';
end

strvcat(test{1},test{2},test{3},test{4},test{5},test{6})
end